### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by sdairs** [cloudera/dbt-impala#14]
Python 3.10 introduced some breaking changes that have not yet been fixed in dbt-core https://github.com/dbt-labs/dbt-core/issues/4974 

Until this is fixed, dbt-impala will not work with Python 3.10.

You may see errors such as

```
  >Runtime Error
  PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

**Comment by sdairs** [comment]
@tovganesh  Have we double checked impyla works with 3.10 yet?

**Comment by tovganesh** [comment]
@sdairs I installed 3.10.3 locally using pyenv, and tried to reproduce the error - but I was able to run basic dbt tests without issue (I pip3 installed fresh dbt-core and dbt-impala to the new env). Can you elaborate where exactly this error is coming from?

**Comment by sdairs** [comment]
Running `dbt debug` fails when connecting to the Impala endpoint 

```
dbt-core 1.0.4
dbt-impala 1.0.4
Python 3.10.3
macOS-10.16-x86_64-i386-64bit
```

```
dbt_impala_demo:
  outputs:
    dev:
     type: impala
     host: ****
     port: 443
     dbname: dbt_demo
     schema: dbt_demo
     user: abrown
     password: ****
     auth_type: ldap
     use_http_transport: true
     use_ssl: true
     http_path: ****
  target: dev
```
